#ifndef NETWORK_PROGRAMMING_HOMEWORK_2_NPUTILITY_H
#define NETWORK_PROGRAMMING_HOMEWORK_2_NPUTILITY_H

int stringHash(const char* src, size_t len);

#endif // NETWORK_PROGRAMMING_HOMEWORK_2_NPUTILITY_H

